version: '3'
services:
  influxdb:
    image: influxdb:2.0
    ports: 
      - '8086:8086'
    volumes: 
      - influxdb-storage:/var/lib/influxdb
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes: 
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on: 
      - influxdb
    environment: 
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_URL=${INFLUXDB_URL}
  monitor:
    build:
      context: .
    volumes: 
      - /sys:/sys
    environment: 
      - OPEN_WEATHER_API_KEY=${OPEN_WEATHER_API_KEY}
      - OPEN_WEATHER_ZIP_CODE=${OPEN_WEATHER_ZIP_CODE}
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - LOGGER_NAME=${LOGGER_NAME}
    depends_on: 
      - influxdb
    privileged: true
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - '80:80'
    depends_on: 
      - grafana
volumes: 
  influxdb-storage:
  grafana-storage: